ND-737 corrceted the spacing errors

diff --git a/.github/workflows/dependabot-pr-to-jira.yml b/.github/workflows/dependabot-pr-to-jira.yml
--- a/.github/workflows/dependabot-pr-to-jira.yml
+++ b/.github/workflows/dependabot-pr-to-jira.yml
@@ -56,16 +56,16 @@ jobs:
         run: |
           echo "Searching for issues with the 'Dependabot' label and '${{ env.REPO_NAME }}' label in project 'ND'..."
 
-        # URL-encode the REPO_NAME for safety (in case there are special characters)
+          # URL-encode the REPO_NAME for safety (in case there are special characters)
           REPO_NAME_ENCODED=$(echo "${{ env.REPO_NAME }}" | jq -sRr @uri)
 
           JQL_QUERY="project = ND AND labels in (Dependabot, \"$REPO_NAME_ENCODED\") AND status in (Backlog)"
 
           # Perform the GET request with the JQL query
           response=$(curl -s -u $JIRA_USERNAME:$JIRA_API_TOKEN \
-          -X GET \
-          -H "Content-Type: application/json" \
-          "$JIRA_URL/rest/api/2/search?jql=$JQL_QUERY")
+            -X GET \
+            -H "Content-Type: application/json" \
+            "$JIRA_URL/rest/api/2/search?jql=$JQL_QUERY")
 
           # Save the response to a file
           echo "$response" > jira_search_response.json
@@ -77,15 +77,15 @@ jobs:
 
           # Check if the response is valid JSON
           if echo "$response" | jq -e . >/dev/null 2>&1; then
-          # Extract the issue key of the first issue if any are found
-          issue_id=$(echo "$response" | jq -r '.issues[0].key // "null"')
-          echo "ISSUE_ID=$issue_id" >> $GITHUB_ENV
+            # Extract the issue key of the first issue if any are found
+            issue_id=$(echo "$response" | jq -r '.issues[0].key // "null"')
+            echo "ISSUE_ID=$issue_id" >> $GITHUB_ENV
           else
-          echo "Invalid JSON response"
-          exit 1
+            echo "Invalid JSON response"
+            exit 1
           fi
 
-        # Step: Create Jira ticket if none found
+      # Step: Create Jira ticket if none found
       - name: Create Jira ticket
         if: (env.ISSUE_COUNT == 0)
         id: create-jira-ticket
@@ -99,7 +99,8 @@ jobs:
           create_response=$(curl -s -u $JIRA_USERNAME:$JIRA_API_TOKEN \
              -X POST \
              -H "Content-Type: application/json" \
-                          --data "{\"fields\":{\"project\":{\"key\":\"ND\"},\"summary\":\"Dependabot PRs for ${{ env.REPO_NAME }}\",\"description\":\"Repository : ${{ env.REPO_NAME }} \\n $PR_DESCRIPTION\",\"issuetype\":{\"name\":\"Task\"},\"labels\":[\"Dependabot\", \"${{ env.REPO_NAME }}\"]}}" \
+             --data "{\"fields\":{\"project\":{\"key\":\"ND\"},\"summary\":\"Dependabot PRs for ${{ env.REPO_NAME }}\",\"description\":\"Repository : ${{ env.REPO_NAME }} \\n $PR_DESCRIPTION\",\"issuetype\":{\"name\":\"Task\"}}}" \
+             "$JIRA_URL/rest/api/2/issue")
           echo "$create_response"
 
           new_issue_id=$(echo "$create_response" | jq -r '.key')
